name: Deploy to Render

on:
  workflow_run:
    workflows: ["Python CI"]
    types: [completed]
    branches: [main]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to Render via API
      run: |
        curl -X POST "https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys" \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
          -H "Content-Type: application/json" \
          -d '{"clearCache": "do_not_clear"}' \
          -w "\nHTTP Status: %{http_code}\n"
      
    - name: Wait for deployment
      run: |
        echo "Waiting for deployment to complete..."
        sleep 30
        echo "Deployment triggered successfully!" 